### ISSUE TITLE
[SUBGRAPH] Add docs for "Stream period" entity

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/docs#12]
Related to: https://github.com/superfluid-finance/protocol-monorepo/issues/464

## Notes

It should wait until "stream period" is released to the v1 subgraph.

**Comment by hellwolf** [comment]
@saflamini  Is this one ready for next week protocol subgraph 1.1 release?

**Comment by saflamini** [comment]
just made a new commit to docs and added an example.

It's just StreamPeriod that's new correct?

**Comment by hellwolf** [comment]
Yea.

I saw that you pushed the update to the public already, though we haven't released yet. We will get it released today.
