### ISSUE TITLE
[SUBGRAPH] Custom subgraph example queries

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/docs#13]

**Comment by 0xdavinchee** [comment]
This can only be done through the UI, still unsure what sort of privileges are required for this though.

**Comment by hellwolf** [comment]
@saflamini are we happy with the subgraph example queries on console graphql explorer?

**Comment by saflamini** [comment]
Looks good for now yes. I will work on getting interactive examples into docs soon as well

**Comment by hellwolf** [comment]
Cool thanks!
