### ISSUE TITLE
Proposal: Superfluid Content Bounties

### ISSUE THREAD

**Issue by ademidun** [superfluid-finance/docs#22]
# Superfluid Content Bounty Proposal

Summary: People create Superfluid tutorials and Superfluid pays them.

  

A [Superfluid Bounty Program](https://docs.superfluid.finance/superfluid/resources/bounty-program) already [exists](https://github.com/orgs/superfluid-finance/projects/17/), you can just add tutorial and content bounties.

## Why This is Important

Good documentation is important for onboarding users. For example, Stripe’s [great documentation](https://greeeg.com/en/issues/what-makes-stripe-api-so-great) is a big [reason](https://document360.com/blog/tear-down-of-stripe-knowledge-base) why so many developers use it for web2 payments. Superfluid can be the Stripe of web3 payments documentation. More tutorials makes it easier for more people to use Superfluid in their projects which creates more material for tutorials and repeat. A powerful [flywheel effect](https://www.atlassian.com/blog/strategy/flywheel-effect-10-lessons) for getting more developers on Superfluid. More tutorials will also allow more [bounties](https://github.com/orgs/superfluid-finance/projects/17/) to get completed

  

I [used](https://github.com/atilatech/smart/commit/24f789bca1c0d6356079b0753a8233c03d6458c2) the Superfluid [Money Streaming API](https://docs.superfluid.finance/superfluid/developers/interactive-tutorials/money-streaming-1) for [my ETHNYC hackathon project](https://github.com/atilatech/smart). The Superfluid team that attended ETHNYC may remember the demo I gave to at your table, it was about [Harberger Tax](https://yos.io/2018/11/18/harberger-taxes/)  [NFTs](https://github.com/atilatech/smart/blob/master/server/contracts/HarbegerNFT.sol). I really love the idea of streamable money and I love what Superfluid is building. However, the [documentation](https://docs.superfluid.finance/superfluid/developers/interactive-tutorials) was very difficult to use. Here are just a few examples:

1.  It didn’t tell me what packages to install ([related issue](https://github.com/superfluid-finance/docs/issues/18))
    
2.  No indication that I needed a faucet to get xDAI and no instructions on how to get some
    
3.  The CodeSandbox iFrame embed was too slow and too squished to use
    
4.  Necessary Information was spread across multiple pages and there were no videos
    

	1.  Quickstart information should be all on one page with [copy-paste friendly code](https://glebbahmutov.com/blog/make-example-code-copy-pastable/)
    
	2.  Videos were on a separate section at the bottom and missing timestamps
    

Usually, when a more established software project lacks good official documentation, people will use the community tutorials. However, Superfluid’s nascentness means there’s currently a lack of community tutorials. Incentivising the community to create tutorials is an effective solution.

## Deliverables

-   Blog post tutorial: (e.g. how to start, update and stop a Superfluid stream in React)
    
-   Optional: Video tutorial accompanying the blog post
    
-   Optional: Twitter Thread or similar social media post summarizing the tutorial
    

## Examples of Past Tutorials I’ve Made

I would love to do one of these bounties. Here are some of my qualifications:

-   [How to Build a Multi-Chain NFT Marketplace](https://atila.ca/blog/tomiwa/how-to-build-a-multi-chain-nft-marketplace-on-ethereum-polygon-and-binance-smart-chain-using-solidity-react-hardhat-and-ethersjs) ([video](https://www.youtube.com/watch?v=2XLkgUvnNJo), [twitter thread](https://twitter.com/tomiwa1a/status/1533540286554513409))
    
-   [How to add Ethereum & Binance Payments w/ React and Ethers.js](https://atila.ca/blog/tomiwa/how-to-add-ethereum-and-binance-payments-to-a-react-website-with-metamask-and-ethersjs/) ([video](https://www.youtube.com/watch?v=VPo3mn9DFTk))
    
-   [How to Get Paid with Crypto Scholarships and Hackathons](https://atila.ca/blog/tomiwa/travel-the-world-for-free-while-getting-paid-with-crypto-scholarships-and-hackathons) ([video](https://www.youtube.com/watch?v=_JGJHMM3Fok), [twitter thread](https://twitter.com/tomiwa1a/status/1534517805298552832), [tiktok](https://www.tiktok.com/@atila.tech/video/7108380632547446022))
    

## Future Ideas

-   I would love to make more Superfluid tutorials (e.g [streamable cash flow](https://github.com/superfluid-finance/protocol-monorepo/tree/dev/examples/tradeable-cashflow) NFT [superapp](https://docs.superfluid.finance/superfluid/developers/developer-guides/super-apps))

**Comment by joeljesu** [comment]
Thanks Tomiwa! We've got the Wave Pool out to reward people creating content on Superfluid: https://docs.superfluid.finance/superfluid/resources/superfluid-wave-pool

**Comment by ademidun** [comment]
Amazing to see this come to life and the fact that you remembered to update this issue 7 months after I posted about it is really impressive. Great work @sunnyjaycer and Superfluid team!
