### ISSUE TITLE
Create two-step console demo

### ISSUE THREAD

**Issue by kobuta23** [superfluid-finance/docs#3]
First step, all-in-one script:
1. run a live goerli testnet instance
2. create admin user()
3. call the faucet, prefund local admin account
4. upgrade daix 
5. create other users (alice, bob, carol)

Second step:
admin.flow(bob, 100)

Third step:
show link to stream page

**Comment by hellwolf** [comment]
@kobuta23 ditto on this one, sync with @pi0neerpat

**Comment by hellwolf** [comment]
scrap it
